//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public tbl_Employee()
        {
            this.tbl_AppRole = new HashSet<tbl_AppRole>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> MajorSkill { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Contact { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string LLId { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsUsResources { get; set; }
        public Nullable<bool> IsContractor { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<tbl_AppRole> tbl_AppRole { get; set; }
    }
}
