//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_App
    {
        public tbl_App()
        {
            this.tbl_AppAgency = new HashSet<tbl_AppAgency>();
            this.tbl_AppDomain = new HashSet<tbl_AppDomain>();
            this.tbl_AppRole = new HashSet<tbl_AppRole>();
            this.tbl_AppServer = new HashSet<tbl_AppServer>();
            this.tbl_AppTech = new HashSet<tbl_AppTech>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StagedTo { get; set; }
        public Nullable<int> PID { get; set; }
        public string DEVUrl { get; set; }
        public string StageUrl { get; set; }
        public string ProdUrl { get; set; }
        public string SourcePath { get; set; }
        public string DocsRepo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<tbl_AppAgency> tbl_AppAgency { get; set; }
        public virtual ICollection<tbl_AppDomain> tbl_AppDomain { get; set; }
        public virtual ICollection<tbl_AppRole> tbl_AppRole { get; set; }
        public virtual ICollection<tbl_AppServer> tbl_AppServer { get; set; }
        public virtual ICollection<tbl_AppTech> tbl_AppTech { get; set; }
    }
}
