//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AppRole
    {
        public int AppId { get; set; }
        public int EmpId { get; set; }
        public int AppRoleId { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_App tbl_App { get; set; }
        public virtual tbl_AppRoleMaster tbl_AppRoleMaster { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
    }
}
