//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Server
    {
        public tbl_Server()
        {
            this.tbl_AppServer = new HashSet<tbl_AppServer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public string Stage { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string FingerPrint { get; set; }
        public string Host { get; set; }
        public string FolderPath { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<tbl_AppServer> tbl_AppServer { get; set; }
    }
}
